### ISSUE TITLE
How can I test the code that sec 4.2 LiDAR scene flow in paper?

### ISSUE THREAD

**Issue by Czy-coder** [gengshan-y/expansion#15]
Firstly, thanks for your great works and code sharing! I have read your papar in detail and learned lots of useful konwledge. I follow your readme and have  implemented the val and test in the KITTI-2015. Now, I want to do the LIDAR scene flow in the paper sec 4.2, but I don't find the kitti15list_val_lidar.py in the dataloader folder. Can you provide the relevant code with LIDAR scene flow, please? I really long to study the section that LIDAR scene flow and implemente its function.

**Comment by gengshan-y** [comment]
Thanks for your interest! I've uploaded the dataloader files. It may take some time to re-organize the code of LiDAR scene flow. Please let me know if some specific part is needed (e.g., evaluation).

**Comment by Czy-coder** [comment]
Thanks for your reply! I need the part which compares prior work on 42 KITTI validation images(LiDAR scene flow) in the paper sec4.2 evaluation protocol.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gengshan-y/expansion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月4日(星期天) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gengshan-y/expansion] How can I test the code that sec 4.2 LiDAR scene flow in paper? (#15)





 
Thanks for your interest! I've uploaded the dataloader files. It may take some time to re-organize the code of LiDAR scene flow. Please let me know if some specific part is needed (e.g., evaluation).

**Comment by gengshan-y** [comment]
The [precomputed results](https://github.com/gengshan-y/expansion#precomputed-results) and [eval scripts](https://github.com/gengshan-y/expansion/blob/master/lidar-scene-flow.ipynb) are added to the repo.
