### ISSUE TITLE
Assumption of orientation is not always true

### ISSUE THREAD

**Issue by ahangchen** [gengshan-y/expansion#2]
In 3.1, there is an assumption that orientation is unchanged, but when camera's rotation is not identity, the orientation will change
(for example, a car with camera turns around at road corner). Is there anything I misunderstand about orientation?

**Comment by gengshan-y** [comment]
You are right about the assumption. When the camera is rotating, optical expansion computed from optical flow fields is not equivalent to motion-in-depth. 

However, the camera rotation is relatively easy to remove by rotational homograph (assuming you already have R from visual/inertial odometry methods)

**Comment by ahangchen** [comment]
Got it, thank's for your reply.
