### ISSUE TITLE
Evaluate on KITTI

### ISSUE THREAD

**Issue by player1321** [gengshan-y/expansion#6]
Hello,
When running `bash run_eval.sh` I got `No such file or directory: '$datapath/training/expansion/000000_10.pfm'`. I checked the code and found:
`# gt`
`gt_oe = disparity_loader(expansionp[fp])`
`gt_logexp = -np.log(gt_oe)`
`oemask = gt_oe>0`
So shall I generate the .pfm files before running the evaluation?
If so, could you provide some examples to show how to generate them?

**Comment by gengshan-y** [comment]
Hi, thanks for bringing this up! I've uploaded it. Please see the updated [readme file](https://github.com/gengshan-y/expansion#evaluate-on-kitti).

**Comment by player1321** [comment]
Got it.
Thanks a lot!
