### ISSUE TITLE
ground-truth motion-in-depth

### ISSUE THREAD

**Issue by player1321** [gengshan-y/expansion#8]
Hi,
As mentioned in your paper, the ground-truth motion-in-depth should be computed using the depth of corresponding points over two frames:
![image](https://user-images.githubusercontent.com/38416786/97151485-85b45800-17aa-11eb-804c-37968deaf981.png)
But it seems that in your code, you compute this using the depth in the same pixel position?
Line 126 in depthloader.py:
![image](https://user-images.githubusercontent.com/38416786/97152986-b85f5000-17ac-11eb-8ee6-03c77d54cfce.png)
Line 50 in depthloader.py:
![image](https://user-images.githubusercontent.com/38416786/97152935-a67dad00-17ac-11eb-974c-24bda6ff3f13.png)

Since `Z = depth`, `dis0 = P0[2]` means that `dis0` corresponds to the pixel coordinates of `d1` and similarly `flow3d[:,:,2]` corresponds to the pixel coordinates of `d2`, so when you generating the ground-truth motion-in-depth in Line 548 in VCN_exp.py by `gt_dchange = (1+gt_f3d[:,2]/gt_depth)`, which means `(1 + flow3d[:,:,2]/dis0)`, you are actually computing `d1/d2`?
Is this the reason why you can simply using `disp1 = disp0/tau` in your notebook demo?

**Comment by gengshan-y** [comment]
d1 and d2 (or disp1, disp2) correspond to the same 3D point, which is moved over time and projected onto two camera coordinate frames. The projection on the first frame is (xcoord, ycoord, d1) and the projection on the second frame is (xcoord + x_flow,ycoord+y_flow,d2). This is the parameterization of scene flow on KITTI. 

Let me know if you have further questions.

**Comment by player1321** [comment]
Thanks a lot for your patient reply. I'm a freshman in this direction.
Does this parameterization still hold for the depth estimation methods like monodepth2 mentioned in your work?
If I want to compare the `disp1` from your method, i.e., `disp1_expansion = disp0/tau`, with that from monodepth2 directly, i.e. `disp1_monodepth2 = monodepth2Model(img1)`, shall I warp `disp1_monodepth2` following the optical flow?

**Comment by gengshan-y** [comment]
Hi, `disp1_expansion = disp0/tau` is defined at the 1st coordinate frame. To compare with `disp1_monodepth2 = monodepth2(Image 1)`, which is defined at the 2nd coordinate frame, you can either (1) warp disp1_monodepth2 to the 1st frame using forward optical flow, as this paper and KITTI sceneflow did, or (2) push disparity values in disp1_expansion to the 2nd frame using forward optical flow as you mentioned.

**Comment by player1321** [comment]
Got it, thank you very much.
