### ISSUE TITLE
Obtaining depth maps from optical expansion

### ISSUE THREAD

**Issue by paulacarbo07** [gengshan-y/expansion#9]
Hi there,
I read in your paper that we can obtain depth from optical expansion. Is there any script available to get depth maps via any of the two methods that are mentioned (time-to-contact or triangulation)?

Also, have you ever compared your depth estimation to for example MonoDepth2 with any specific metrics? I am interested in seeing if it is going to be more accurate.

Thanks very much for the repo and best regards!

**Comment by gengshan-y** [comment]
It's updated [here](https://github.com/gengshan-y/expansion#rigid-depth-inference). I didn't report quantitative results in the paper, but flow-triangulated depth and TTC depth is more accurate than monocular depth in general (in terms of depth metrics).

**Comment by paulacarbo07** [comment]
That's great, thanks so much! I'll test it out as soon as I have some free time. Cheers!
